apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: postgres
resources:
- postgres-storageclass.yaml
- postgres-persistentvolume.yaml
- postgres-service.yaml
- postgres-statefulset.yaml

configMapGenerator:
  - name: postgres-cm
    envs:
    - config/postgres.env
    
generatorOptions:
  disableNameSuffixHash: true # use a static name