apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: postgres
spec:
  storageClassName: mysc
  volumeMode: Filesystem
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mypv05"
  persistentVolumeReclaimPolicy: Delete