apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app       
    spec:
      containers:
      - name: todo-app-monolith
        image: binarylavender/todo-app-monolith:v1
        envFrom:
          - configMapRef:
              name: todo-app-cm
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
          - containerPort: 4000